name: Capstone Backend
values:
  - key: baseUrl
    value: 'http://localhost:5000'
    enabled: true
    type: default
  - key: token
    value: ''
    enabled: true
    type: default
  - key: photoId
    value: ''
    enabled: true
    type: default
